// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/// @notice Generic adapter for Groth16 verifier contracts generated by arkworks-solidity-verifier.
/// @dev It forwards raw proof/publicInputs bytes to a target verifier's `verifyTx(...)`.
contract Groth16VerifierAdapter {
    address public immutable verifier;
    bytes4 public immutable verifySelector;
    uint256 public immutable publicInputWordLength;

    constructor(address verifierAddress, bytes4 selector, uint256 inputWordLength) {
        require(verifierAddress != address(0), "Invalid verifier");
        verifier = verifierAddress;
        verifySelector = selector;
        publicInputWordLength = inputWordLength;
    }

    function verify(bytes calldata proofBytes, bytes calldata publicInputBytes) external view returns (bool) {
        // Groth16 proof is expected to be 8 uint256 words.
        if (proofBytes.length != 32 * 8) {
            return false;
        }
        if (publicInputBytes.length != uint256(publicInputWordLength) * 32) {
            return false;
        }

        bytes memory callData = bytes.concat(verifySelector, proofBytes, publicInputBytes);
        (bool ok, bytes memory result) = verifier.staticcall(callData);
        if (!ok || result.length < 32) {
            return false;
        }

        return abi.decode(result, (bool));
    }
}
